-- BBS

DROP TABLE tbl_bbs;
CREATE TABLE tbl_bbs (
    BBS_ID	NUMBER	NOT NULL	PRIMARY KEY,
    BBS_P_ID	NUMBER	DEFAULT 0,	
    BBS_WRITER	nVARCHAR2(50)	NOT NULL,	
    BBS_DATE	VARCHAR2(10)	NOT NULL,	
    BBS_TIME	VARCHAR2(10)	NOT NULL,	
    BBS_SUBJECT	VARCHAR2(125)	NOT NULL,	
    BBS_TEXT	VARCHAR2(1000)	NOT NULL,	
    BBS_COUNT	NUMBER	DEFAULT 0	
);

CREATE SEQUENCE SEQ_BBS
START WITH 1 INCREMENT BY 1;