SELECT * FROM v$database;
SELECT * FROM dba_all_database;

DROP TABLE tbl_board;
DROP TABLE tbl_bbs;
CREATE TABLE tbl_bbs (

    BBS_ID	NUMBER	NOT NULL	PRIMARY KEy,
    BBS_P_ID	NUMBER	NOT NULL,	
    BBS_WRITER	nVARCHAR2(50)	NOT NULL,	
    BBS_DATE	VARCHAR2(10)	NOT NULL,	
    BBS_TIME	VARCHAR2(10)	NOT NULL,	
    BBS_SUBJECT	VARCHAR2(125)	NOT NULL,	
    BBS_TEXT	VARCHAR2(1000)	NOT NULL,	
    BBS_VIEWS	NUMBER	DEFAULT 0	


);

SELECT * FROM tbl_bbs;

-- IN, ALL
SELECT * FROM tbl_bbs
WHERE SUBSTR(BBS_DATE,0,7) IN ('2019-01','2019-03','2019-05');

SELECT * FROM tbl_bbs
WHERE SUBSTR(BBS_DATE,0,7) <= ALL ('2019-01','2019-02','2019-05');



-- 서브쿼리 연습1

-- WHERE 절에서 사용하는 SUB QUERY :  이걸 왜 쓰는거야@!!
SELECT * FROM tbl_bbs
WHERE BBS_ID IN (SELECT BBS_ID FROM tbl_bbs);

SELECT * FROM tbl_bbs
WHERE BBS_ID IN (
    SELECT BBS_ID FROM tbl_bbs
    WHERE SUBSTR(BBS_DATE,0,7) = '2019-03'
);





